#!/usr/bin/python3
import os
import sys

from qlib import *
from filelock import FileLock


ids = sys.argv[1]


with FileLock(lock_file):
    if not state_file.exists():
        sys.exit(0)
    state = read_state()

idlist = ids.split(',')
for id in idlist:
    if id in state['jobs']:
        j = state['jobs'][id]
        print('%s %s %s' % (id, j['state'], j['error']))
