from typing import Any

NEW: str
DONE: str
FAILED: str
CANCELED: str
INITIAL: Any
FINAL: Any
PMGR_LAUNCHING_PENDING: str
PMGR_LAUNCHING: str
PMGR_ACTIVE_PENDING: str
PMGR_ACTIVE: str
TMGR_SCHEDULING_PENDING: str
TMGR_SCHEDULING: str
TMGR_STAGING_INPUT_PENDING: str
TMGR_STAGING_INPUT: str
AGENT_STAGING_INPUT_PENDING: str
AGENT_STAGING_INPUT: str
AGENT_SCHEDULING_PENDING: str
AGENT_SCHEDULING: str
AGENT_EXECUTING_PENDING: str
AGENT_EXECUTING: str
AGENT_STAGING_OUTPUT_PENDING: str
AGENT_STAGING_OUTPUT: str
TMGR_STAGING_OUTPUT_PENDING: str
TMGR_STAGING_OUTPUT: str
CANCELING = CANCELED
PENDING = PMGR_LAUNCHING_PENDING
PENDING_LAUNCH = PMGR_LAUNCHING_PENDING
LAUNCHING = PMGR_LAUNCHING
PENDING_ACTIVE = PMGR_ACTIVE_PENDING
ACTIVE_PENDING = PMGR_ACTIVE_PENDING
ACTIVE = PMGR_ACTIVE
UNSCHEDULED = TMGR_SCHEDULING_PENDING
SCHEDULING = TMGR_SCHEDULING
PENDING_INPUT_STAGING = TMGR_STAGING_INPUT_PENDING
STAGING_INPUT = TMGR_STAGING_INPUT
ALLOCATING_PENDING = AGENT_SCHEDULING_PENDING
ALLOCATING = AGENT_SCHEDULING
PENDING_EXECUTION = AGENT_EXECUTING_PENDING
EXECUTING_PENDING = AGENT_EXECUTING_PENDING
EXECUTING = AGENT_EXECUTING
PENDING_OUTPUT_STAGING = TMGR_STAGING_OUTPUT_PENDING
STAGING_OUTPUT = TMGR_STAGING_OUTPUT
UMGR_SCHEDULING_PENDING = TMGR_SCHEDULING_PENDING
UMGR_SCHEDULING = TMGR_SCHEDULING
UMGR_STAGING_INPUT_PENDING = TMGR_STAGING_INPUT_PENDING
UMGR_STAGING_INPUT = TMGR_STAGING_INPUT
UMGR_STAGING_OUTPUT_PENDING = TMGR_STAGING_OUTPUT_PENDING
UMGR_STAGING_OUTPUT = TMGR_STAGING_OUTPUT
