name: build-website

on:
  push:
    branches: [ main, web_site ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Fetch tags
        run: git fetch --all --tags
      -
        name: Build Website
        run: /bin/bash web/build.sh
      -
        name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: web-build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
